---

- name: Set timezone for server
  community.general.timezone:
    name: "{{ settimezoneto }}"

- name: Install a list of packages on behalf of ntpsec
  ansible.builtin.apt:
    pkg:
    - ntpsec
    autoremove: yes
    purge: true

- name: Template a file to /etc/ntpsec/ntp.conf
  ansible.builtin.template:
    src: templates/etc/ntpsec/ntp.conf.j2
    dest: /etc/ntpsec/ntp.conf
    owner: root
    group: root
    mode: '0644'

- name: Make sure service unit ntpsec is enabled and running
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: ntpsec

...
